# S02 T04: Numeric Coding Practice

### Exercise 1

*Create a function that takes an one dimension Array, gives you a basic statistical summary of the data. And if it detects that the array has more than one dimension, it must display an error message.*

In [4]:
import numpy as np
from scipy import stats

def data_summary(array):
    print(stats.describe(array))

In [5]:
array_one = np.array([2, 1, 5, 3, 7, 4, 6, 8])
data_summary(array_one)

DescribeResult(nobs=8, minmax=(1, 8), mean=4.5, variance=6.0, skewness=0.0, kurtosis=-1.2380952380952381)


### Exercise 2

*Create a function that creates a NxN square of random numbers between 0 and 100.*

In [25]:
def square():
    return np.random.choice(np.arange(101), size=(5, 5))

In [31]:
array_square= square()
print(array_square)

[[ 9 12 83 22 33]
 [73 13 28 73 44]
 [38 21 15 20 36]
 [72 90 61 65 23]
 [58  3 63 18  6]]


### Exercise 3

*Create a function that, given a two-dimensional table, calculates totals per row and per column.*

In [32]:
def totals_calculation(array):
    row_sums = array.sum(axis=1)
    column_sums = array.sum(axis=0)
    print("The total per rows is:",row_sums,", and the total per columns is:",column_sums)

In [33]:
totals_calculation(array_square)

The total per rows is: [159 231 130 311 148] , and the total per columns is: [250 139 250 198 142]


### Exercise 4

*Manually implement a function that calculates the correlation coefficient. Find out more about its uses and interpretation.*

In [34]:
def correlation_coeficient(x,y):
    correlation = np.corrcoef(x, y)
    print(correlation)

In [36]:
x=np.arange(30,40)
y=np.array([5,3,7,6,10,14,19,35,94,58])

correlation_coeficient(x,y)

[[1.         0.80323888]
 [0.80323888 1.        ]]
